# Aula 10 - Variáveis aleatórias discretas
___


<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Simulando as vendas de um corretor](#simulando-as-vendas)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)
    - [Exercício 7](#ex7)

In [1]:
import numpy as np
import random
import pandas as pd

___

<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$50,00 a cada novo seguro que um corretor vende. A probabilidade de um cliente adquirir o seguro é de 0,20. 

1. Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.
1. Qual a probabilidade de um corretor ganhar apenas R\\$50,00?

Vamos considerar os eventos:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i = S_i^C$: o cliente $i$ não compra o seguro.

Pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

Listando todas as possíveis combinações de eventos, temos:

Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão 
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 100

Estamos interessados no valor da comissão de um corretor. Para isso, vamos definir a variável aleatória:

- $C$: valor da comissão do corretor.

Assim, o item 2 pode ser interpretado como: qual é o valor de $P(C=50)$?

Consultando a tabela calculada acima, vemos que $P(C=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $C$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [56]:
from scipy.stats import binom

a,b = binom.stats([0, 50, 100], [0.64, 0.32, 0.04])

print("Esperanca:",sum(a))


Esperanca: 20.0


In [52]:
valor_medio = 0.64*0 + 0.32*50 + 0.04*100
print(valor_medio)
variancia = ((0-valor_medio)**2)*0.64 + ((50-valor_medio)**2)*0.32 + ((100-valor_medio)**2)*0.04
print(variancia)

20.0
800.0


### Simulando as vendas de um corretor

Para termos uma melhor intuição sobre o significado do valor esperado e variância de $C$, ou seja, $E(C)$, vamos realizar uma simulação. Como conhecemos as probabilidades, podemos simular as vendas de um determinado corretor. Considere a função a seguir:

In [14]:
# Simula uma venda ocorrendo com probabilidade 0.2
def simula_venda():
    p = random.random()
    if p <= 0.2:
        vendeu = True
    else:
        vendeu = False
    return vendeu

# Simula a comissao de duas abordagens a clientes
def simula_comissao_total(valor_da_comissao):
    venda1 = simula_venda()
    venda2 = simula_venda()
    comissao = 0
    if venda1:
        comissao += valor_da_comissao
    if venda2:
        comissao += valor_da_comissao
    return comissao

Vamos repetir a simulação `n` vezes. A série a seguir contém a comissão de 10 simulações.

In [15]:
def simula_n_vezes(n, valor_da_comissao, valor_fixo):    
    simulacoes = []
    for i in range(n):
        comissao = simula_comissao_total(valor_da_comissao) + valor_fixo
        simulacoes.append(comissao)
    return pd.Series(simulacoes)
    
n = 10
valor_da_comissao = 50
simulacoes = simula_n_vezes(n, valor_da_comissao, 0)
simulacoes

0     0
1     0
2    50
3    50
4     0
5    50
6     0
7     0
8    50
9     0
dtype: int64

Vamos verificar a comissão média recebida nas simulações. Além disso, vamos imprimir também a variância.

In [57]:
media = simulacoes.mean()
variancia = simulacoes.var(ddof=0)  # Pesquise o que significa o argumento ddof=0
print('Média = {0}\nVariância = {1}'.format(media, variancia))

Média = 19.894
Variância = 794.028764


Esse valor é possívelmente bastante diferente do valor esperado calculado no [exercício 1](#ex1). Vamos verificar o que acontece quando aumentamos a quantidade de simulações:

<div id="n-simulacoes"></div>

In [82]:
valor_da_comissao = 50
for i in range(1, 6):
    n = 10**i
    simulacoes = simula_n_vezes(n, valor_da_comissao, 0)
    comissao_media = simulacoes.mean()
    variancia = simulacoes.var(ddof=0)
    print('Simulando n = {0} vezes:'.format(n))
    print('    comissão média = {0}'.format(comissao_media))
    print('    variância = {0}'.format(variancia))

Simulando n = 10 vezes:
    comissão média = 25.0
    variância = 1125.0
Simulando n = 100 vezes:
    comissão média = 22.5
    variância = 868.75
Simulando n = 1000 vezes:
    comissão média = 19.1
    variância = 740.19
Simulando n = 10000 vezes:
    comissão média = 19.775
    variância = 791.6993749999998
Simulando n = 100000 vezes:
    comissão média = 20.0535
    variância = 796.83213775


<div id="ex2"></div>

### EXERCÍCIO 2

Observando os resultados acima, qual você esperaria ser a média e variância de 1000000000000 simulações? Você não deve realizar essa simulação, apenas discutir qual você espera ser o resultado. Por quê?


Neste caso, a média e a variância simuladas seriam muito próximas do valor ideal calculado

## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- Nova comissão será a comissão atual mais um fixo de R$ 20,00;
- Nova comissão será o dobro da atual comissão.

1. Escolha qual delas é melhor para aumentar o ganho de um corretor. Justifique sua resposta.

<div id="ex3"></div>

### EXERCÍCIO 3

Construa a distribuição de probabilidade e calcule o valor esperado e a variância de cada opção. 

Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 20
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 70
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 70
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 120



valor_medio = 0.64*20 + 0.32*70 + 0.04*120
print(valor_medio)
variancia = ((20-valor_medio)**2)*0.64 + ((70-valor_medio)**2)*0.32 + ((120-valor_medio)**2)*0.04
print(variancia)

In [86]:
Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 100
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 100
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 200

40.0
800.0


In [90]:
valor_medio = 0.64*0 + 0.32*100 + 0.04*200
print(valor_medio)
variancia = ((0-valor_medio)**2)*0.64 + ((100-valor_medio)**2)*0.32 + ((200-valor_medio)**2)*0.04
print(variancia)

40.0
3200.0


<div id="ex4"></div>

### EXERCÍCIO 4

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 40.0 reais ; 40.0 reais*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

<div id="ex5"></div>

### EXERCÍCIO 5

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 3200.0 reais^2*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

<div id="ex6"></div>

### EXERCÍCIO 6

Vamos verificar as propriedades da esperança e da variância. Utilize a função `simula_n_vezes` como mostrado [nesta célula](#n-simulacoes) para realizar simulações das duas novas opções de comissão para os seguintes valores de `n`: 10, 100, 1000, 10000, 100000.

In [106]:
valor_da_comissao = 50
for i in range(1, 6):
    n = 10**i
    simulacoes = simula_n_vezes(n, valor_da_comissao, 20)
    comissao_media = simulacoes.mean()
    variancia = simulacoes.var(ddof=0)
    print('Simulando n = {0} vezes:'.format(n))
    print('    comissão média = {0}'.format(comissao_media))
    print('    variância = {0}'.format(variancia))

Simulando n = 10 vezes:
    comissão média = 45.0
    variância = 625.0
Simulando n = 100 vezes:
    comissão média = 39.5
    variância = 944.75
Simulando n = 1000 vezes:
    comissão média = 39.8
    variância = 782.96
Simulando n = 10000 vezes:
    comissão média = 39.885
    variância = 786.3367750000002
Simulando n = 100000 vezes:
    comissão média = 39.97
    variância = 800.4991000000001


In [123]:
valor_da_comissao = 100
for i in range(1, 6):
    n = 10**i
    simulacoes = simula_n_vezes(n, valor_da_comissao, 0)
    comissao_media = simulacoes.mean()
    variancia = simulacoes.var(ddof=0)
    print('Simulando n = {0} vezes:'.format(n))
    print('    comissão média = {0}'.format(comissao_media))
    print('    variância = {0}'.format(variancia))

Simulando n = 10 vezes:
    comissão média = 40.0
    variância = 2400.0
Simulando n = 100 vezes:
    comissão média = 40.0
    variância = 3600.0
Simulando n = 1000 vezes:
    comissão média = 40.4
    variância = 3367.840000000001
Simulando n = 10000 vezes:
    comissão média = 39.54
    variância = 3200.5884000000005
Simulando n = 100000 vezes:
    comissão média = 39.643
    variância = 3167.5325510000007


<div id="ex7"></div>

### EXERCÍCIO 7

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

ESCREVA SUA RESPOSTA AQUI

# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)